### ISSUE TITLE
The size of the search bar's content pane is limited

### ISSUE THREAD

**Issue by schloett** [EEXCESS/chrome-extension#10]
Hence, on the first resize, it gets smaller, even if you try to enlarge it. It should be up to the user to decide on the size (if she wants it to span the whole screen area, then well, it should do so). Moreover on Win 7, there appear scrollbars (see the image below).

![screenshot](https://cloud.githubusercontent.com/assets/4618499/9172753/eedc3af4-3f75-11e5-97c2-163f738096c0.PNG)

**Comment by LadyBytes** [comment]
It's limited on purpose due to the iframe's behaviour when exceeding a certain size (it gets a bit recalcitrant). I removed the limitation for you to test the behaviour without it. :) Just tell me what you'd prefer!

**Comment by schloett** [comment]
Domesticate it :P
For me it seems to work fine when I remove the aspectRatio, which also feels more natural. Could you check, if it remains recalcitrant without aspectRatio?

P.S.: scroll bars are still there (you could create an own issue for that, if you want to close this one)

**Comment by LadyBytes** [comment]
Scrollbars are removed! 

I'd like to keep the ratios because they could come in handy for future visualization widgets. 
It may only have seemed to work for you, because after resizing without them, the iframe (due to still having it's own ratio) didn't cover all available space anymore (see screenshot below), which rendered the free space draggable and resizable. But whenever the mouse pointer enters the iframe while dragging, the resize stops. I I opened a new issue for this: #12 

<img width="346" alt="screen shot 2015-08-18 at 09 19 23" src="https://cloud.githubusercontent.com/assets/3264627/9325095/4d31fcd6-4590-11e5-80e1-f45d45059dc5.png">
