### ISSUE TITLE
Resizable SearchBar Components

### ISSUE THREAD

**Issue by LadyBytes** [EEXCESS/chrome-extension#3]
Using jQuery-UI's resizable() method.

resizable() example:
https://jqueryui.com/resizable/

remember new size:
http://stackoverflow.com/questions/8468680/jquery-ui-resizable-returning-the-size

**Comment by schloett** [comment]
It might be necessary to provide a function that exposes size modification to external components. You would probably want to remember the size using localStorage. For the chrome-extension, this might be problematic, since the searchBar is injected into webpages and the localStorage is tied to that particular domain. So the storage needs to be done in the background-script and passed on to the contentscript.

**Comment by LadyBytes** [comment]
The extension's size and position are now preserved over multiple domains and reloads using Chrome's local storage and jQuery-ui's resizable() and draggable() methods.

On the first resize the tabs-area jumps to the side corrsponding to the used resize handle (i.e. if the user wants to resize using the left/west handle, the area relocates to "right: 0;"). This apparently happens due to a bug concerning the combined usage of resize and drag or resize and a fixed location. 
It affects only the very first resize, the ones taking place after that, on another website or after a page refresh aren't affected anymore.

My current workaround enables the resize functionality only after a dragging took place, which successfully prevents jumping.

Info on the bug:
http://bugs.jqueryui.com/ticket/3628
http://bugs.jqueryui.com/ticket/6939
http://stackoverflow.com/questions/22721706/jquery-resize-causes-jump
http://aleembawany.com/2009/01/25/jquery-resizable-draggable-bug-workaround/

**Comment by chseifert** [comment]
Valid solution :) Could you monitor the bugs, and in case they'll get fixed check the functionality again?

**Comment by LadyBytes** [comment]
Should work now with a more user friendly workaround, see issue #8
